import api from './api';
import { Transaction } from '../types/transaction';

// Omit 'id' because it's auto-generated by the database.
type CreateTransactionData = Omit<Transaction, 'id'>;

/**
 * Fetches all transactions from the API.
 */
export const getTransactions = async (): Promise<Transaction[]> => {
  try {
    const response = await api.get('/transactions');
    return response.data;
  } catch (error) {
    console.error("Error fetching transactions:", error);
    throw error;
  }
};

/**
 * Creates a new transaction.
 * @param data The transaction data to be sent to the API.
 */
export const createTransaction = async (data: CreateTransactionData): Promise<Transaction> => {
  try {
    const response = await api.post('/transactions', data);
    return response.data;
  } catch (error) {
    console.error("Error creating transaction:", error);
    throw error;
  }
};